### ISSUE TITLE
regarding mixed-signal SoC section

### ISSUE THREAD

**Issue by kunalg123** [praharshapm/vsdmixedsignalflow#1]
Hi Praharsha
In your mixed-signal SoC section, there is lot of text, which I feel, can be reduced by adding one image. You can take up image either from VSD website or you can try creating one. And add that image to this section

**Comment by praharshapm** [comment]
Hi Sir,
I have reduced the text content by summarizing the main points and I have also added an image. You might want to take a look at it and close the issue.
